server:
  port: 9005
spring:
  application:
    name: consumer-sentinel-gateway-depart
  cloud:
    gateway:
      # 配置开启定位器
      discovery:
        locator:
          enabled: true
      routes:
        - id: depart_route1
          uri: lb://consumer-sentinel-depart
          predicates:
            - Path=/sentinel/**
        - id: depart_route2
          uri: lb://provider02Nacosconfig
          predicates:
            - Path=/provider/**
    sentinel:
      filter:
        url-patterns: /**
      transport:
        dashboard: 172.20.10.2:8888
        port: 8722
        eager: true
        client-ip: 172.20.10.10
    #    loadbalancer:
#      # 关闭Ribbon的负载均衡器
#      ribbon:
#        enabled: false
    nacos:
      discovery:
        server-addr: 172.20.10.2:8840,172.20.10.2:8845,172.20.10.2:8849
feign:
  client:
    config:
      default:
        #连接超时时间
        connectTimeout: 5000
        #数据读取超时是时间
        readTimeout: 5000
  sentinel:
    enabled: true

# 指定要使用的负载均衡策略 # <clientName>. <clientConfigNameSpace>.NFLoadBalancerRuleClassName
provider02Nacosconfig:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

management:
  endpoint:
    web:
      exposure:
        include: '*'