server:
  # ?????8080
  port: 8080
spring:
  application:
    name: consumer01-depart
  cloud:
#    loadbalancer:
#      # 关闭Ribbon的负载均衡器
#      ribbon:
#        enabled: false
    nacos:
      discovery:
        server-addr: 172.20.10.2:8840,172.20.10.2:8845,172.20.10.2:8849
feign:
  client:
    config:
      default:
        #连接超时时间
        connectTimeout: 5000
        #数据读取超时是时间
        readTimeout: 5000

# 指定要使用的负载均衡策略 # <clientName>. <clientConfigNameSpace>.NFLoadBalancerRuleClassName
provider02Nacosconfig:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule